CXX         = c++
CXXFLAGS    = -Wall -Werror -Wextra -std=c++98
CXXDEBUG    = -fsanitize=address -g
RM          = rm -f

.PHONY      : all
all         :
	@./do.sh

.PHONY      : clean
clean       :

.PHONY      : fclean
fclean      : clean

.PHONY      : re
re          : fclean all